### PR TITLE
v4.0.0-beta.420.4

### LINKED ISSUE #2470: [Bug]: Docker compose deployment has empty COOLIFY_FQDN and COOLIFY_URL
### Description

The Coolify pre defined variables `COOLIFY_FQDN` and `COOLIFY_URL` are empty when using a `Docker Compose` Git based resource. It's empty on all services.

### Minimal Reproduction (if possible, example repository)

* Create a `Docker Compose` app (done via GitHub app)
* Configure app (URL)
* Deploy
* Run `env` inside any of the containers

### Exception or Error

_No response_

### Version

v4.0.0-beta.297

### LINKED ISSUE #6134: [Bug]: $COOLIFY_FQDN in Environment Variables contains the scheme https://
### Error Message and Logs

`$COOLIFY_FQDN` in Environment Variables contains the scheme `https://`.
This makes it difficult to pass it to variables that expect a domain like:

```sh
PHX_HOST=$COOLIFY_FQDN
```

Workaround here is to use application logic to remove the scheme.

```ex
  def remove_scheme(url) do
    url
    |> String.replace_prefix("https://", "")
    |> String.replace_prefix("http://", "")
  end
```

ChatGPT says that the FQDN should not include the scheme, port or query params.

### Steps to Reproduce

1.  Add `PHX_HOST=$COOLIFY_FQDN` to environment variables
2. Perform a build
3. Open terminal and run `env`
4. The env shows a scheme and a domain

### Coolify Version

v4.0.0-beta.420.3

### Are you using Coolify Cloud?

No (self-hosted)

### LINKED ISSUE #6141: [Bug]: Literal env variables seems broken
### Error Message and Logs

No error message just not working.

### Steps to Reproduce

1. Deploy vaultwarden
2. Generate a password with `openssl rand -base64 48`
3. Generate a hash of the previously generated password with `echo -n "${PREVIOUSLY_GENERATED_PASSWORD}" | argon2 "$(openssl rand -base64 32)" -e -id -k 65540 -t 3 -p 4` 4. Set in SERVICE_PASSWORD_64_ADMIN env variable the generated hash that should look like something like "$argon2id$v=19$m=65540,t=3,p=4$eHhNc2ZZV2ltNFptNTlzZ2hQbDFwN2dQVFEvYndtZjZ3RXRYc0NIV0VkVT0$abRZxmaVRe8vqt9..." and check is Literal box
5. Deploy
6. Head of over to /admin ui enter the token and see that it doesn't work

### Example Repository URL

_No response_

### Coolify Version

v4.0.0-beta.420.3

### Are you using Coolify Cloud?

No (self-hosted)

### Operating System and Version (self-hosted)

Ubuntu 24.04

### Additional Information

Feel free to check that [doc](https://github.com/dani-garcia/vaultwarden/wiki/Enabling-admin-page#secure-the-admin_token) from vaultwarden to setup the admin page. The plaintext token works fine so I'm assuming It's a problem of interpolation ?

### LINKED ISSUE #6142: [Bug]: Service Postiz shows No Available Server error
### Error Message and Logs

Deploy `postiz` using the one click template:
- The postiz container is throwing some errors
- So the container health check fails
- So the proxy throws No Available Server due to failing health check
Image

Image

### Steps to Reproduce

1. Create new resource on Coolify
2. Select `postiz` from the service list
3. Click the deploy button
4. Visit the app url

### Example Repository URL

https://github.com/coollabsio/coolify/blob/v4.x/templates/compose/postiz.yaml

### Coolify Version

v4.0.0-beta.420.3

### Are you using Coolify Cloud?

No (self-hosted)

### Operating System and Version (self-hosted)

Alpine Linux v3.21

### Additional Information

- The template is using `latest` tag so something might got changed on their new version
- Based on the container logs it seems like we are missing some environment values
- I might try to find a fix and pin the version from `latest` to a specific working version

### PR DESCRIPTION
**Pull request by andrasbacsai**
# POSSIBLE BREAKING CHANGE
- fix(envs): enhance COOLIFY_URL and COOLIFY_FQDN variable generation for better compatibility for applications and services.
  -  **Switched URL with FQDN in case of applications, so they are correct now.**

--- 
- feat(envs): New environment variables for `docker compose` based application. You can use `SERVICE_FQDN_<serviceName>` and `SERVICE_URL_<serviceName>` the same way as in services. For details check this: https://github.com/coollabsio/coolify/issues/6124#issuecomment-3045186382
- fix(redis): Cleanup old jobs on Coolify start.
- fix(database): Unsupported database with SSL.
- fix(jobs): Sentinel update job fails if compose is invalid for a service/app.
- fix(installscript): Add Cachyos support + reuse env variable for public ip.
- fix(envs): Generate literal env variables better.

# Issues
- fix https://github.com/coollabsio/coolify/issues/6142
- fix https://github.com/coollabsio/coolify/issues/6134
- fix https://github.com/coollabsio/coolify/issues/6141
- fix https://github.com/coollabsio/coolify/issues/2470

### CODE REVIEW

File: app/Jobs/ApplicationDeploymentJob.php [hunk 1]
```diff
@@ -920,6 +924,22 @@ private function save_environment_variables()
...
+            if ($this->build_pack === 'dockercompose') {
+                $domains = collect(json_decode($this->application->docker_compose_domains)) ?? collect([]);
+
+                // Generate SERVICE_FQDN & SERVICE_URL for dockercompose
+                foreach ($domains as $forServiceName => $domain) {
+                    $parsedDomain = data_get($domain, 'domain');
+                    if (filled($parsedDomain)) {
+                        $parsedDomain = str($parsedDomain)->explode(',')->first();
+                        $coolifyUrl = str($parsedDomain)->after('://')->before(':')->prepend(str($parsedDomain)->before('://')->append('://'));
+                        $coolifyFqdn = str($parsedDomain)->replace('http://', '')->replace('https://', '')->before(':');
```
Comment (Arnaud-IFEA) [inline app/Jobs/ApplicationDeploymentJob.php]: Hello,
imho maybe use `parse_url` or your `spatie` url lib to manipulate scheme and hostname. It would be easier to read and understand.

File: app/Jobs/ApplicationDeploymentJob.php [hunk 2]
```diff
@@ -936,6 +956,21 @@ private function save_environment_variables()
...
+            if ($this->build_pack === 'dockercompose') {
+                $domains = collect(json_decode(data_get($this->preview, 'docker_compose_domains'))) ?? collect([]);
+
+                // Generate SERVICE_FQDN & SERVICE_URL for dockercompose
+                foreach ($domains as $forServiceName => $domain) {
+                    $parsedDomain = data_get($domain, 'domain');
+                    if (filled($parsedDomain)) {
+                        $parsedDomain = str($parsedDomain)->explode(',')->first();
+                        $coolifyUrl = str($parsedDomain)->after('://')->before(':')->prepend(str($parsedDomain)->before('://')->append('://'));
+                        $coolifyFqdn = str($parsedDomain)->replace('http://', '')->replace('https://', '')->before(':');
```
Comment (Arnaud-IFEA) [inline app/Jobs/ApplicationDeploymentJob.php]: same remark here.

File: app/Jobs/ApplicationDeploymentJob.php [hunk 3]
```diff
@@ -1347,9 +1347,16 @@ private function set_coolify_variables()
...
-            $this->coolify_variables .= "COOLIFY_URL={$url} ";
+            $fqdnWithoutPort = str($fqdn)->after('://')->before(':')->prepend(str($fqdn)->before('://')->append('://'));
+            $url = str($fqdn)->replace('http://', '')->replace('https://', '')->before(':');
+            if ((int) $this->application->compose_parsing_version >= 3) {
+                $this->coolify_variables .= "COOLIFY_URL={$fqdnWithoutPort} ";
+                $this->coolify_variables .= "COOLIFY_FQDN={$url} ";
+            } else {
+                $this->coolify_variables .= "COOLIFY_URL={$fqdnWithoutPort} ";
+                $this->coolify_variables .= "COOLIFY_FQDN={$url} ";
+            }
```
Comment (Arnaud-IFEA) [inline app/Jobs/ApplicationDeploymentJob.php]: It seems that the conditional block is no longer needed.

File: app/Jobs/ApplicationDeploymentJob.php [hunk 4]
```diff
@@ -1347,9 +1347,16 @@ private function set_coolify_variables()
             $fqdn = $this->preview->fqdn;
         }
         if (isset($fqdn)) {
-            $this->coolify_variables .= "COOLIFY_FQDN={$fqdn} ";
-            $url = str($fqdn)->replace('http://', '')->replace('https://', '');
-            $this->coolify_variables .= "COOLIFY_URL={$url} ";
+            $fqdnWithoutPort = str($fqdn)->after('://')->before(':')->prepend(str($fqdn)->before('://')->append('://'));
+            $url = str($fqdn)->replace('http://', '')->replace('https://', '')->before(':');
```
Comment (Arnaud-IFEA) [inline app/Jobs/ApplicationDeploymentJob.php]: semantically `$fqdn` shouldn't have to deal with scheme. Maybe in a refacto or the v5.x you should stick to `$fqdn=domain name` and `$url=scheme+fqdn+path`. It would be less confusing.

my 2 cents.

**Comment by BjoernRave** [comment]
do you think we could get the signoz service in here as well? looks like the PR is ready https://github.com/coollabsio/coolify/pull/5386 and its a very powerful service

File: app/Jobs/ApplicationDeploymentJob.php (hunk 1 above)
Comment (andrasbacsai) [reply app/Jobs/ApplicationDeploymentJob.php]: I refactored, thanks for the suggestion!

File: app/Jobs/ApplicationDeploymentJob.php (hunk 2 above)
Comment (andrasbacsai) [reply app/Jobs/ApplicationDeploymentJob.php]: I refactored, thanks for the suggestion!

**Comment by andrasbacsai** [comment]
> do you think we could get the signoz service in here as well? looks like the PR is ready #5386 and its a very powerful service

This release is for fixes & features. The next one, I will check Signoz and if everything is good, I will add it.
